import subprocess
import pandas as pd
import matplotlib.pyplot as plt
import os
import skrf as rf

def run_xyce_simulation(netlist_name, output_name):
    # 1. Run Xyce
    # -log: helps debug if the .s6p file isn't found
    command = ["Xyce", netlist_name, "-o", output_name]
    
    print(f"🚀 Running Xyce simulation on {netlist_name}...")
    result = subprocess.run(command, capture_output=True, text=True)
    
    if result.returncode != 0:
        print("❌ Simulation Failed!")
        print(result.stderr)
        return None
import time
t1 = time.time()
# Execution
run_xyce_simulation("netlist.cir", "sim_results")
t2 = time.time()
print(f"Simulation took {t2 - t1} seconds")

import skrf as rf
from matplotlib import pyplot as plt

# 1. Load the Touchstone file generated by Xyce
# This automatically handles the 4 ports and the complex data
net = rf.Network('sim_results.s4p')

# 2. Plot Magnitude (dB) for S11 and S21
plt.figure(figsize=(10, 6))
net.plot_s_db()

plt.title('Transformer Analysis via scikit-rf')
plt.grid(True)
plt.show()