TOOLTIPS = {
    "config_panel_btn": "Open configuration panel for files, optimizer, simulator, and goals.",
    "viz_panel_btn": "Open visualization panel with plots and status tables.",
    "help_btn": "Open the COBRA tutorial and project info.",
    "action_btn": "Start, pause, or resume optimization.",
    "stop_btn": "Stop optimization after the current step.",
    "onnx_btn": "Browse for the surrogate ONNX model. Can be generated with ORCA.",
    "netlist_btn": "Browse for the circuit netlist generated by Qucs-S (.cir).",
    "add_manual_btn": "Add a parameter manually.",
    "add_onnx_btn": "Add parameters from ONNX model inputs. Options here are automatically parsed from the ONNX file.",
    "add_net_btn": "Add parameters from netlist elements. Options here are automatically parsed from the netlist",
    "add_goal_btn": "Create a design goal constraint. The final optimized design will try to meet all goals as well as possible.",
    "zoom_btn": "Zoom the S-parameter plot to the goal frequency range.",
    "geometry_file_btn": "Browse for a custom ORCA geometry Python file.",
    "optuna_sampler_combo": "Select the Optuna sampler strategy. SimulatedAnnealingSampler requires optunahub.",
    "optuna_pruner_combo": "Select an optional Optuna pruner. Pruners stop unpromising trials early to save time, but may miss good solutions.",
    "finetune_cb": "Run a few Palace iterations at the end to verify or refine surrogate results. Ensures final design actually meets goals via EM simulation.",
    "ft_optimizer_combo": "Reuse the surrogate optimizer state or switch to a different one (e.g., gradient descent).",
    "freq_unit_combo": "Unit for min/max frequency.",
}

TUTORIAL_HTML = """
<html>
  <body>
    <h2>COBRA GUI Tutorial</h2>
    <p>
      COBRA (Circuit-Level Open-Source Based RFIC AI-Assisted Optimizer) combines
      surrogate-model S-parameter prediction, circuit simulation, and goal-driven
      optimization for RFIC workflows.
    </p>

    <h3>Quick Start</h3>
    <ol>
      <li>Create a netlist for your circuit in Qucs-S. Include tunable elements (i.e. an SNP file) for optimization.</li>
      <li>Select your ORCA-generated ONNX model.</li>
      <li>Select the generated circuit netlist (.cir for Qucs-S).</li>
      <li>Choose the optimizer, simulator, and iteration limit.</li>
      <li>Add optimization parameters and design goals, e.g. S11_dB < -10 between 120 and 130 GHz.</li>
      <li>Click Start Optimization and wait until it completes.</li>
    </ol>

    <h3>Configuration Panel</h3>
    <ul>
      <li><b>ONNX Model</b>: Surrogate model used to predict S-parameters. Can be generated with ORCA.</li>
      <li><b>Netlist</b>: Circuit netlist for simulation. Can be generated with Qucs-S.</li>
      <li><b>Optimizer</b>: Optuna-based optimizer settings, including sampler and pruner. Advanced setting.</li>
      <li><b>Simulator</b>: Circuit simulator that runs a SPICE simulation on the entire circuit (Xyce by default).</li>
      <li><b>Max Iterations</b>: Stops after the given number of optimization steps.</li>
    </ul>

    <h3>Optimization Parameters</h3>
    <ul>
      <li><b>Add Manual</b>: Define a parameter by hand.</li>
      <li><b>Add from ONNX</b>: Import parameters from the model inputs defined in the ONNX file.</li>
      <li><b>Add from Netlist</b>: Import additional parameters from the netlist, e.g. Capacitors (C1, C2).</li>
    </ul>

    <h3>Design Goals</h3>
    <p>
      Add targets like S11_dB or S21_dB with optional frequency ranges.
      Use min and/or max limits to define the constraint. Weight defines how important this goal is relative to others.
    </p>

    <h3>Fine-Tuning (Optional)</h3>
    <p>
      Enable finetuning to run Palace simulations after goals are reached.
      Ensures the final design actually meets goals via EM simulation, but will take much longer (multiple minutes per palace iteration).
      Choose an ORCA geometry preset or a custom geometry class such that COBRA can generate and mesh the GDS files.
    </p>

    <h3>Visualization Panel</h3>
    <ul>
      <li><b>S-Parameters</b>: Current and previous iteration curves.</li>
      <li><b>Goal Losses</b>: Per-goal loss history over iterations.</li>
      <li><b>Goal Status</b>: Current values, targets, and loss coloring.</li>
    </ul>

    <h3>About</h3>
    <p>
      GitHub: <a href="https://github.com/DI-PASSIONATE/COBRA">https://github.com/DI-PASSIONATE/COBRA</a><br />
      Organization: <a href="https://www.lites.tf.fau.de/">Chair for Intelligent Technical Electronics and Systems (LITES) at FAU</a><br />
      Project: <a href="https://www.elektronikforschung.de/projekte/di-passionate">DI-PASSIONATE</a><br />
      Authors: David Lurz, Gianluca Simone
    </p>

    <h3>Found a Bug or Have a Feature Request?</h3>
    <p>
      Please submit an <a href="https://github.com/DI-PASSIONATE/COBRA/issues/new">issue on GitHub.</a>
    </p>

  </body>
</html>
"""


def tooltip(key: str) -> str:
    return TOOLTIPS.get(key, "")
